### ISSUE TITLE
Currently doesn't work with the Wildcard Images feature as the carousel uses the Actor Image, not the Token Image. Allow the use of the Token Image.

### ISSUE THREAD

**Issue by hoyer1066** [death-save/combat-carousel-public#55] opened 2021-01-27 21:48 UTC
The current setup basically prevents the use of the Wildcard feature of Foundry, as tokens look different on the carousel than they do on the scene. This means that you are forced to either not use Combat Carousel, not use multiple Token Images for the same actor (Wildcard), or create duplicate actors for each different Token Image (which is a lot more work and negates the usefulness of the Wildcard feature).

The solution would be for Combat Carousel to either primarily use the Token Image rather than the Actor Image, showing what each token looks like on the scene, or to have an option to choose between the two (either for each token or overall).

There are no alternatives that allow both the use of Combat Carousel and the Wildcard Feature.
![Carousel-Wildcard](https://user-images.githubusercontent.com/77966438/106058613-66023800-60e9-11eb-8af6-e5b9a57f04f1.JPG)

**Comment by eclarke12** [comment] 2021-01-27 22:07
duplicate of #8 and fixed in v0.2.0 (currently closed alpha: https://www.patreon.com/posts/46720823)

**Closed by eclarke12** 2021-01-27 22:07 UTC
Labels: duplicate, enhancement
