### ISSUE TITLE
If minimized, don't maximize when the active player changes

### ISSUE THREAD

**Issue by Klindel** [death-save/combat-carousel-public#47] opened 2020-11-25 23:18 UTC
Some players don't have the screen real estate for the carousel to be up 100% of the time.  However, if they minimize it by clicking the icon, as soon as the active player changes, all the icon's reappear.  It should respect the players choice to hide the carousel and only reappear when the player chooses to

**Comment by eclarke12** [comment] 2020-11-26 00:04
duplicate of #43

**Closed by eclarke12** 2020-11-26 00:04 UTC
Labels: duplicate, enhancement
