### ISSUE TITLE
OSE ruleset and Combat Carousel

### ISSUE THREAD

**Issue by Seanny101** [death-save/combat-carousel-public#41] opened 2020-10-28 23:46 UTC
*I have Foundry 0.7.5 and am using OSE ruleset (which is very nice btw) with the Combat Carousel Module (also very good). Ihave the bug where Hit Points are not shown in a green bar in Combat carousel in OSE whereas in other rulesets like PF1 and PF2 for example the little green bar is shown. Ideas?
In the other rulesets I am using stock standard Combat carousel and have not had to change any settings to get green health bar in Combat Carousel.What can I do to get this to appear in the OSE ruleset ,it is very handy and I need it?

**Comment by eclarke12** [comment] 2020-10-29 00:23
Currently the health attribute is hard coded if I remember correctly. A
future update will allow configuration so it supports more systems

**Comment by Seanny101** [comment] 2020-10-30 02:45
Cool look forward to the module working better with OSE.

**Comment by eclarke12** [comment] 2020-12-20 01:16
this is covered/duplicate of #6

**Closed by eclarke12** 2020-12-20 01:16 UTC
Labels: bug, duplicate
